### PR TITLE
add register_json

### PR DESCRIPTION
**Pull request by cswingle**
Adds `register_json` to the `Connection` and `Pool` classes.  Essentially copied from the `register_hstore` code.

### CODE REVIEW

**Comment by haizaar** [comment]
Thanks.

**Comment by cswingle** [comment]
Thanks for merging.  I probably should have bumped the version number, etc., so that pip and friends would know whether they're getting a version with or without it.

**Comment by haizaar** [comment]
Well, from time to time we tag new version and update PyPi. Lets give your code some time and we'll push it then. I prefer not to update version before then.

**Comment by cswingle** [comment]
> Lets give your code some time and we'll push it then. I prefer not to update version before then.

Fair enough.  Thanks.

**Pull request merged**
